name: Publish Github Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+" # MAJOR.MINOR (1.0: y, 1.0a0: n, 1.0.1: n)

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ncipollo/release-action@v1
        with:
          body: |
            Changelog: https://sphinx.silverrainz.me/strike/changelog.html
